language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    # - ROS_DISTRO="kinetic" ROS_REPO=main
    # - ROS_DISTRO="kinetic" ROS_REPO=testing
    # #- ROS_DISTRO="kinetic" PRERELEASE=true
    # - ROS_DISTRO="melodic" ROS_REPO=main UPSTREAM_WORKSPACE='github:mojin-robotics/ur_msgs#melodic-devel'
    # - ROS_DISTRO="melodic" ROS_REPO=testing
    # #- ROS_DISTRO="melodic" PRERELEASE=true UPSTREAM_WORKSPACE='github:mojin-robotics/ur_msgs#melodic-devel'
    - ROS_DISTRO="noetic" ROS_REPO=main UPSTREAM_WORKSPACE='github:mojin-robotics/ur_msgs#melodic-devel'
    - ROS_DISTRO="noetic" ROS_REPO=testing
    #- ROS_DISTRO="noetic" PRERELEASE=true UPSTREAM_WORKSPACE='github:mojin-robotics/ur_msgs#melodic-devel'

#matrix:
#  allow_failures:
#    - env: ROS_DISTRO="kinetic" ROS_REPO=main
#    - env: ROS_DISTRO="kinetic" ROS_REPO=testing
#    - env: ROS_DISTRO="kinetic" PRERELEASE=true

install:
  - git clone --quiet --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
